### ISSUE TITLE
Add sorting options

### ISSUE THREAD

**Issue by KjmT6459** [CorruptedArk/did-i-take-my-meds#1]
**Is your feature request related to a problem? Please describe.**
Med order is only available in the order they were added.

**Describe the solution you'd like**
Add options to sort as desired. Primary options would be 'Name' and 'Time'.  The only other option I can think of would be 'Type' such as pill or liquid.

**Comment by CorruptedArk** [comment]
This is a good suggestion, I'll try to implement it after I finish the feature additions I'm working on in the complex-time branch

**Comment by CorruptedArk** [comment]
Feature now implemented in the master branch
