### ISSUE TITLE
Disable med without deleting it

### ISSUE THREAD

**Issue by jpameli** [CorruptedArk/did-i-take-my-meds#13]
It would be great if an med could be toggled as "disabled" so it will grayed out or not visible in the main list and not affected by the sorting of the "active" meds.

Background: When you stop taking a med it is still interesting to see the history of the med, but it is not necessary to have it in the main list.

Thanks for the great updates - makes easier to track medication of the whole family :)

**Comment by CorruptedArk** [comment]
I still like this idea, but I'm going to push it back to a later release than the upcoming one

**Comment by CorruptedArk** [comment]
I want to let you know that this feature is currently in the master branch and will be available in the next official release
