### ISSUE TITLE
Notification Actions

### ISSUE THREAD

**Issue by jwsp1** [CorruptedArk/did-i-take-my-meds#15]
I'd welcome notification actions like 
1) Just took it
2) Remind me in 15mins
3) Skip

**Comment by CorruptedArk** [comment]
This is a good idea and worth considering

**Comment by CorruptedArk** [comment]
I've implemented the "just took it" and "remind me" actions, but I don't see a skip button as necessary because swiping away a notification already covers that functionality.

**Comment by jwsp1** [comment]
True. Thanks! :-)
