### ISSUE TITLE
Inhibit notification for doses taken early

### ISSUE THREAD

**Issue by AeliusSaionji** [CorruptedArk/did-i-take-my-meds#16]
Hello!

Today I took my meds 5 minutes before the notification was scheduled.
I marked in the app that I took my notification, but 5 minutes later I got notified anyway.

I think the app should be aware that the notifications is not needed in this context.

Thanks!

**Comment by CorruptedArk** [comment]
Hi, can you provide me with more information about what version you are using? Version 1.1.3 already does this.
