### ISSUE TITLE
Allow entry of meds needed multiple times per day

### ISSUE THREAD

**Issue by ewenger** [CorruptedArk/did-i-take-my-meds#17]
My meds have to be taken X times per day.  It would be helpful to be able to enter values like that.

**Comment by CorruptedArk** [comment]
What version are you using? In the current release this is already possible, but you need to specify the exact times each day.

**Comment by CorruptedArk** [comment]
Without any further information explaining how the feature requested in this issue is not already satisfied by the current release, I'm closing this issue.
