### ISSUE TITLE
Show whether a medication has been taken on the main screen

### ISSUE THREAD

**Issue by KjmT6459** [CorruptedArk/did-i-take-my-meds#2]
**Is your feature request related to a problem? Please describe.**
Having to go into the specific medication screen to double check that it has been taken is slow and unnecessary.

**Describe the solution you'd like**
A sub-line under the name of the medication with "Taken : Yes/No". The already listed time-to-take would have to move to the right most likely.

**Describe alternatives you've considered**
Status could be to the right of the med name.
Could add a checkmark when the dose has been taken.
Dose background color could change to a green once taken.

**Comment by CorruptedArk** [comment]
This is also a very good suggestion! Again, I'll have to add this to a list of features I plan to work on

**Comment by CorruptedArk** [comment]
A taken indicator is now implemented in the master branch
