### ISSUE TITLE
Display how much time has passed since last dose

### ISSUE THREAD

**Issue by kadillaq** [CorruptedArk/did-i-take-my-meds#20]
Hi,
I often miss doses because of my sleep schedule/other issues.
Currently, there is a dose history, but I'd like to clearly see how much time has passed since I took my last dose.
I believe it might help me get a better idea of where I am without having to do the math.
Thanks

**Comment by CorruptedArk** [comment]
This is fairly easy to implement and a good idea. I should be able to add this feature soon

**Comment by CorruptedArk** [comment]
This was about as easy to implement as I thought
