### ISSUE TITLE
Ability to create a widget

### ISSUE THREAD

**Issue by kadillaq** [CorruptedArk/did-i-take-my-meds#21]
Hi,
I use the app a lot and I really like how simple it is.
However, I can easily miss reminders since they are only in notification form. 
I rely a lot on widgets on my phone since they help me get a clear and easy access to information.
I think a simple widget with 1 medication, the elapsed time since the last dose (as mentioned in  #20 ), and a "I took it" button or equivalent.
I don't want the widget to have a list of all medication, I'd like to be able to select the one I want for the current widget if possible.
I hope you consider my request, 
Thanks

**Comment by CorruptedArk** [comment]
I haven't made a widget for an app before, but it's probably not too hard. I like this idea and I'll add it if it's not too complicated

**Comment by CorruptedArk** [comment]
The widget is now available in the latest release
