### ISSUE TITLE
Bug: Reminding every 7 days / once a week not possible

### ISSUE THREAD

**Issue by jwsp1** [CorruptedArk/did-i-take-my-meds#22]
**Describe the bug**
You cannot set the days to 0 or 7. This means you cannot be notified once every week (e.g. always on sunday night).

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: 11
 - Version: [e.g. 1.1.4]
 - Build Location:  F-Droid release

**Comment by CorruptedArk** [comment]
Good catch, I believe I know how to fix it

**Comment by CorruptedArk** [comment]
Also 1.1.4 is almost a month old, F-Droid release is at 1.2.1. I highly recommend updating more frequently if you can
