### ISSUE TITLE
Can't click anything in fdroid version 1.2.4

### ISSUE THREAD

**Issue by DanBenHa** [CorruptedArk/did-i-take-my-meds#24]
**Describe the bug**
I see my med entries but can't click any of them. Can't add new entries. Notifications don't work

**To Reproduce**
1. Go to app
2. Click on anythin
3. App freezes

**Expected behavior**
Ability to see details and add entries.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 XL
 - OS: Android 11
 - Version: 1.2.4
 - F-Droid release

**Comment by DanBenHa** [comment]
Scratch that. I see that 1.2.5 fixes that. Fdroid version is delayed

**Comment by CorruptedArk** [comment]
Yeah, I pushed a fix as soon I caught the bug, but unfortunately F-Droid still released v1.2.4 before v1.2.5 anyway. Unfortunately the bug isn't triggered under all circumstances, so I failed to catch it before the v1.2.4 release. I wish I had a team of dedicated testers to help me find all these edge cases.
