### ISSUE TITLE
Add ability to edit "taken time"

### ISSUE THREAD

**Issue by KjmT6459** [CorruptedArk/did-i-take-my-meds#26]
**Is your feature request related to a problem? Please describe.**
Basically, I'm good enough at noticing the notification and taking my meds. But I often end up forgetting to verify in the app that I did. I then re-notice the notification later and then tell it I took it. The point is obviously primarily to know that a dose has been taken at all, but I'd like the option of fixing specific dose timing.

**Describe the solution you'd like**
In specific med menus is the list of times taken. Let me long-tap a time and edit it.

**Describe alternatives you've considered**
I cannot think of an alternative way to do this that would be any better.

**Additional context**
I oughta just get better, but I know I won't. @_@

**Comment by CorruptedArk** [comment]
This feature is now implemented in release v1.5.1
