### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by yarons** [CorruptedArk/did-i-take-my-meds#29]
**Is your feature request related to a problem? Please describe.**
I want to translate this app to Hebrew

**Describe the solution you'd like**
I want to use a localization platform such as Weblate to contribute translation to this app.

**Describe alternatives you've considered**
I can download the strings.xml file and translate it manually.

**Additional context**
Using localization platform will expose the app to many translators that share the same values was the developer, it will surely help senior citizens without English knowledge to keep remembering their meds.

I personally contributed to similar projects in the past, none of them is maintained today.

**Comment by CorruptedArk** [comment]
This is a good idea, and I have already thought about it. The main challenge with using Weblate is finding a web host I can afford that can handling running the service. I am looking at some potential free options, but I am not making enough money at this point to pay for a web server.

**Comment by yarons** [comment]
@CorruptedArk This is an open source project, you can apply for the open source plan on Weblate.

**Comment by CorruptedArk** [comment]
I see, you're right. I missed that when I was looking through their pricing options previously.

**Comment by yarons** [comment]
LOL it was pretty vague not so long ago but now they're offering trial period and meanwhile they'll scan your project to see if it's in fact open source and act accordingly.

**Comment by CorruptedArk** [comment]
I've been working on the Weblate integration since you submitted this issue, and I wanted you to know that the Weblate project is open. I'm still waiting on the approval for the libre plan, but since this project is GPLv3+, and I have no intent to change it, it's only a matter of time. Given that, I'm going to close this issue

**Comment by yarons** [comment]
Oh no! Don't close it without adding the link to it :)

Thank you!

**Comment by CorruptedArk** [comment]
Oh yeah, my bad, I forgot to mention that there's a link in README and I'm pretty sure I added one to CONTRIBUTING. But based on recent commits, it looks like you found it
