### ISSUE TITLE
Tapping notification should take you into the dose

### ISSUE THREAD

**Issue by KjmT6459** [CorruptedArk/did-i-take-my-meds#3]
**Is your feature request related to a problem? Please describe.**
Currently, when tapping reminder notifications, you're taken to the main screen and have to remember the med you just tapped.

**Describe the solution you'd like**
Tapping notification should take you into the dose of the med that you're being reminded of.

**Comment by CorruptedArk** [comment]
I agree, and I've already thought of this one. I put it on the back burner for the release because it's a bit annoying to implement based on how the medication data is accessed in the app. It can be done though

**Comment by ChrislyBear-GH** [comment]
Totally agree. I just wanted to make the same suggestion.

**Comment by CorruptedArk** [comment]
This feature is now implemented in master
