### ISSUE TITLE
Option of normal font size

### ISSUE THREAD

**Issue by OliverLew** [CorruptedArk/did-i-take-my-meds#33]
I understand the current app texts are are giant for accessibility concerns, but can I have an option to make them normal size?

**Comment by CorruptedArk** [comment]
I don't see why not, how big is normal in your mind? Are you familiar with sizes in sp units?

**Comment by OliverLew** [comment]
I am not familiar with Android development, but is there a default font size, or relative description like "normal" "large" etc.? Most apps on my phone seems quite consistent, not sure how they are doing it.

**Comment by CorruptedArk** [comment]
Yeah, there are some conventional sizes for small, medium, and large. To be honest, I just went with values that looked right for me, but I can adjust the app to use more standard sizes.

**Comment by CorruptedArk** [comment]
Text views now use standard text sizes, so I'm going to close this issue, but it can be reopened if the new sizes are unsatisfactory
