### ISSUE TITLE
Please increase characters size for translate on weblate, specially for Fastlane component

### ISSUE THREAD

**Issue by caos30** [CorruptedArk/did-i-take-my-meds#34]
Hello, i discovered your software today and i'm 100% fascinated! Excellent opensource initiative. I'm quite sure that it will be translated soon in a really long number of languages!

Said this, i translated almost all the sentences on weblate.org for spanish (castillian) and for a new language (catalan), that i hope you would be able to add asap to the next update :-)

My problem translating some sentences is that it seems you fixed a 500 characters limit for the translation length for those sentences on Fastlane component, and it's really not enough for the most of the "version logs changes"... even the original english text is longer than 500 sometimes ;-)

My suggestion/request is to set at least double length for those "sentences". Please ;-)

I appreciate your cooperation again, thanks!!

**Comment by CorruptedArk** [comment]
Thanks for your translations and thanks for bringing this issue to my attention. The max length was set by default when I set up the Fastlane component on Weblate. I wasn't aware it was limited to only 30 characters. I have just set all strings to ignore the max length setting, so this issue should be resolved.

**Comment by caos30** [comment]
I'm sorry, but it continues to exists the same limit of 500 characters per translation. Look my screenshot below. 

The most curious thing is that the original text (english) has 546 characters.

As i read on weblate HELP, you can set limits for each sentence or leave the system to apply the default limit (usually 10 times the length of the original). But man, i would say that with the DOUBLE of characters is quite enough... at least for european languages.

![imatge](https://user-images.githubusercontent.com/1767547/143097411-895711dd-f4e1-46ab-aca8-b3c4a9c57f6b.png)

**Comment by CorruptedArk** [comment]
I've been trying to fix this issue and it appears that I am unable to change the max length while using the Libre plan for Weblate. Unfortunately, I believe I have to leave it as is. In addition, it appears Weblate removed some recent Fastlane translations while I was trying to sort out repository actions for the component. I have to say that while Weblate is great for making translations more convenient for non-developers, it has created some new headaches for me. As a work-around, when you run into a translation that is too long, you can either submit a pull request with the change or submit it to me in an email. In the case of an email, the contribution will not show up directly in your GitHub activity, but I will tag you in the commit to ensure you still get proper credit for it.

**Comment by caos30** [comment]
Thanks to check that. 
So, i forked on Github the project. And i understand that for "fastlane" translations is enough to duplicate this directory:

' ' '/fastlane/metadata/android/en-US/' ' ' 

to these others:

' ' '
did-i-take-my-meds/fastlane/metadata/android/ca-ES/ (catalan)
did-i-take-my-meds/fastlane/metadata/android/es-ES/ (spanish)
' ' ' 
Please correct me if i'm wrong with this.
And, regarding the other text translations i see that you have them on weblate.org so you will be able to include it on the next version of the app?
Thanks!

**Comment by CorruptedArk** [comment]
You are correct, duplicating the directory with a different language code adds another locale for fastlane. I believe those folders are correct, but I can correct the names later if they're wrong. And yeah, the app string translations are still there, and I intend to include them in the next release.
