### ISSUE TITLE
Additional fields when adding medicines

### ISSUE THREAD

**Issue by KjmT6459** [CorruptedArk/did-i-take-my-meds#4]
**Is your feature request related to a problem? Please describe.**
The description box is nice, but having distinct fields for specific dosing information would be nice.

**Describe the solution you'd like**
Fields for: 
-Amount per dose (mg/ml/etc)
-Amount of doses (X Pill(s)/cap-fulls/etc)
-Take with/without food

**Describe alternatives you've considered**
Other possible fields, though all work well enough in the description box:
-RX#
-Pharmacy
-Refill information

**Comment by CorruptedArk** [comment]
Another good suggestion, but it's definitely lower priority than the other suggestions. I'll try to get to it after the others

**Comment by CorruptedArk** [comment]
I want to let you know that the feature requested in this issue are currently in progress, and most of them are implemented in the master branch. They should all be ready in the next official release
