### ISSUE TITLE
Label to be translated "Birth control schedule"

### ISSUE THREAD

**Issue by caos30** [CorruptedArk/did-i-take-my-meds#43]
Hello, i want to say first that your app is fantastic. I love and i need it every day. Thanks a lot.

I'm collaborating with spanish and catalan translation. In fact, i've passed today 2 hours checking again the translations in those languages, because after a month using your app i really understand now 100% of the meaning of each sentence in the interface ;-)

Said this, i see that in the last version of the app (1.6.1) you introduced a new text "Birth control schedule" that it looks fantastic. I've tried it and i suppose that it will be loved by some women :-)

But please, can you create a new "translatable text" on weblate? Thanks!!

By the way, these would be the translations in my languages (if you want to add it):

- spanish: "Pastillas anticonceptivas"
- catalan: "Pastilles anticonceptives"

Thanks in advance for your help and for your great work.

**Comment by CorruptedArk** [comment]
The ability to translate that string will automatically get added when I merge master into weblate-string-translations
