### ISSUE TITLE
1.6.4 crashing

### ISSUE THREAD

**Issue by derpyderpaderp** [CorruptedArk/did-i-take-my-meds#55]
**Describe the bug**
Version 1.6.4 crashes when clicking on any of the prescriptions I have setup in the app. This is not happening in 1.6.3. It does this every time I open the app and click on any of my prescriptions. 

**To Reproduce**
1. Go to 'DITMM'
2. Click on any of the prescriptions and crash
3. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [ galaxy s10]
 - OS: [Android 12.0]
 - Version: [e.g. 1.6.4]
 - Build Location: [F-Droid release]

**Additional context**
As stated this doesn't happen in 1.6.3. Maybe has to do something with the update? If you need more information let me know and I'll try and get it to you ASAP. thank you for the app.

**Comment by derpyderpaderp** [comment]
Nvm seen it was fixed with 1.6.5

**Comment by CorruptedArk** [comment]
Duplicate of #53
