### ISSUE TITLE
Suggestions about notifications

### ISSUE THREAD

**Issue by ChrislyBear-GH** [CorruptedArk/did-i-take-my-meds#7]
Hi,

I like the app and with it my medication regimen is easier to manage.

To make it even better I have two suggestions:

1. Make the notification permanent, i.e. you shouldn't be able to swipe a medication reminder away. The "I just took it" button should be the only way to get rid of a notification.
2. Add the "I just took it" action to the notification as a notification action. It would be convenient to confirm a dose right at the notification.

Why is this a big deal?
If I press the "Clear all notifications" button the dose reminder also vanishes. This should be avoided!

What do you think about those suggestions? Are they feasible? How long do you think the implementation would take? Would it be a lot of work?

**Comment by CorruptedArk** [comment]
The suggestion to make the notification persistent is interesting and I'll consider it. I don't plan on adding the action to the notification, but the suggestion in issue #3 is on my to-do list. Does that sound like an acceptable compromise to you?

**Comment by CorruptedArk** [comment]
Okay, I thought about it and changed my mind about the notification action. It is already in the master branch and I intend to publish a release with it soon. I'm going to say no to the persistence though.
