### ISSUE TITLE
Cannot add new meds after last update

### ISSUE THREAD

**Issue by 154pinkchairs** [CorruptedArk/did-i-take-my-meds#9]
It happens when I try to set the schedule. There're no ok/cancel buttons, so after filling the schedule fields and pressing 'Back' button it just clears everything and asks me to fill all schedule fields.

**To Reproduce**
as above

**Expected behavior**
med schedule being added

**Screenshots**
![Screenshot_20210813-074223_Did I Take My Meds.jpg](https://user-images.githubusercontent.com/86662980/129310442-64353302-6682-467b-bad0-28c2b4fd6a81.jpg)
![Screenshot_20210813-074237_Did I Take My Meds.jpg](https://user-images.githubusercontent.com/86662980/129310455-5bd02b6b-b7c5-46df-ac65-b22e2bf98c94.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 Exynos Europe
 - OS: Android 8.0
 - Version: 1.1.0
 - Build Location: Play Store

**Additional context**
My smartphone is set to lower resolution (FHD) to conserve battery, if that's of any importance here.

**Comment by CorruptedArk** [comment]
So what's happening is that there isn't enough room on screen to draw the okay and cancel buttons in the fragment. I think of a long term solution, but I am unable to implement it at the moment due to a power outage where I live. If you increase resolution, do the buttons show up?

**Comment by CorruptedArk** [comment]
My power came back so I was able to work on it. The problem should be fixed in the new update. Let me know if the problem persists once v1.1.1 rolls out to you.
